### ISSUE TITLE
Build and run the C example program within the CI

### ISSUE THREAD

**Issue by paulhowardarm** [veraison/rust-apiclient#8]
### Summary
[This PR](https://github.com/veraison/rust-apiclient/pull/7) introduced a C-callable wrapper of the Rust client, along with a C example program. At the moment, the C example program needs to be built and executed manually. We should make this part of the CI so that it doesn't bit-rot as the interface evolves.

### Requirements
At the moment, there is only one C example program, and it can be found in the `c-wrapper/c-examples/challenge_response` folder of this repo. The new CI step should use its `Makefile` to build the C code. To execute the program, we can use [WireMock](https://wiremock.org) to run a mock Veraison challenge-response API endpoint. The CI should download the WireMock JAR file from [here](https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-jre8-standalone/2.35.0/wiremock-jre8-standalone-2.35.0.jar) and [run the server as a standalone process](https://wiremock.org/docs/running-standalone/) using `java -jar`. The repo already contains a `wiremock` subfolder, which should be used as the server's root directory. Its `mappings` folder contains suitable request/response mocks, implemented to a level for the C example to work. The mappings use template syntax, so ensure that `--global-response-templating` is enabled. The C example will expect the service to be running on port 8080. This is hard-coded in the C source. If this port cannot be used for some reason, then it will be necessary to parameterise the C code either using a command-line arg or a preprocessor macro.

Failure to build the source, or a non-zero exit code from the C program, should result in failure of the CI.

**Comment by thomas-fossati** [comment]
Since https://github.com/veraison/rust-apiclient/pull/19, this is OBE.
